CREATE TABLE IF NOT EXISTS user(
id INT AUTO_INCREMENT,
username VARCHAR(50) NOT NULL,
email VARCHAR(100) NOT NULL,
birthday DATE,
is_active BOOLEAN DEFAULT TRUE,
PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8


CREATE TABLE IF NOT EXISTS user(
id INT AUTO_INCREMENT,
username VARCHAR(50) NOT NULL,
number VARCHAR(100),
position VARCHAR(50),
PRIMARY KEY(id))